name: margaretharmer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63723
title: Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#1b336d'
    - '#4c85a6'
    - '#7e6585'
    - '#f1a7c0'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
